---

- include: epel.yml tags=repos

- name: Install basic packages with yum
  yum: pkg={{ item }} state=installed
  with_items:
    - bison-devel
    - cmake
    - gcc
    - glibc-devel
    - git-core
    - htop
    - make
    - vim
    - zlib-devel
  when: ansible_distribution == 'CentOS'

- name: Configure apt to only use IPv4
  template: src=99force-ipv4 dest=/etc/apt/apt.conf.d/99force-ipv4
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Update apt cache
  apt: update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install basic packages with apt
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - git-core
    - htop
    - sudo
    - vim
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: firewall.yml tags=security,firewall,ssh
- include: ntp.yml tags=ntp,time
- include: security.yml tags=security
- include: ssh.yml tags=ssh,security
- include: sysctl.yml tags=security,kernel
